import Foundation
import PackagePlugin

/// SwiftPM build plugin: reads the package-root `VERSION` file at build
/// time and emits `MCVersion.swift` (containing `MCVersion.app: String`)
/// into MacCleanKit's compilation unit.
///
/// Eliminates the "bump VERSION and ALSO bump a hardcoded constant"
/// double-bookkeeping. Anything that displays the app version (the
/// title-bar subtitle, log lines, About screen) reads `MCVersion.app`
/// directly — works under `swift run` and in the shipped DMG alike.
@main
struct VersionGen: BuildToolPlugin {
    func createBuildCommands(
        context: PluginContext, target: Target
    ) async throws -> [Command] {
        let versionFile = context.package.directoryURL.appendingPathComponent("VERSION")
        let outputDir = context.pluginWorkDirectoryURL
        let outputFile = outputDir.appendingPathComponent("MCVersion.swift")

        // /bin/sh is always available on macOS and is the cheapest way to
        // turn the VERSION file's contents into a Swift source. The
        // `.buildCommand` form rebuilds only when `VERSION` changes thanks
        // to the inputFiles/outputFiles dependency declaration.
        let script = """
        VERSION="$(tr -d '[:space:]' < "\(versionFile.path)")"
        cat > "\(outputFile.path)" <<EOF
        // Generated by VersionGen build plugin from VERSION. Do not edit.
        public enum MCVersion {
            public static let app = "${VERSION}"
        }
        EOF
        """

        return [
            .buildCommand(
                displayName: "Generate MCVersion.swift from VERSION",
                executable: URL(fileURLWithPath: "/bin/sh"),
                arguments: ["-c", script],
                inputFiles: [versionFile],
                outputFiles: [outputFile]
            )
        ]
    }
}
